### ISSUE TITLE
Duplicated line when `Delete Line` is invoked too many times

### ISSUE THREAD

**Issue by thatlittleboy** [texstudio-org/texstudio#108]
### Environment
- TeXstudio: TeXstudio 2.12.9 (hg 2.12.8-48-g60b98db) 
- Qt: 5.8.0
- OS: Windows 10 
- TeX distribution: Miktex 

### Expected behavior
No duplicated line.

### Actual behavior
Duplicated line, though it does go away after clicking something. (See image below)

### How to reproduce
In a new file, perform the key combinations:

1. <kbd>Ctrl</kbd>+<kbd>E</kbd>, type `equation` to get:
```
\begin{equation}
	content
\end{equation}
```

2. <kbd>Ctrl</kbd>+<kbd>Right Arrow</kbd> to jump placeholder to `content`.

3. Type `\sum`, the autocomplete suggestion box should appear. Invoke <kbd>Ctrl</kbd>+<kbd>K</kbd> multiple times (~6 times; the point is to invoke more than the number of lines available in the document), then this happens:
![texstudio_2018-04-09_17-24-04](https://user-images.githubusercontent.com/30731072/38509814-e93da12e-3c1a-11e8-8141-1162326b927f.png)
Note the duplicated line.

4. It gets weirder if you click <kbd>Enter</kbd> to accept the autocomplete suggestion.
![texstudio_2018-04-09_17-26-48](https://user-images.githubusercontent.com/30731072/38509909-31d984b6-3c1b-11e8-813f-90de71d1f63b.png)

**Comment by sunderme** [comment]
fixed in repository

**Comment by thatlittleboy** [comment]
Similar problem so I don't think it warrants a new issue being opened. On the latest version (git 8cf4304), this 'duplicated line' effect still occurs in instances like this:

1. Type something that brings up the autocompleter window: e.g., `\begin`.
2. Press <kbd>Esc</kbd>.

![mwe](https://user-images.githubusercontent.com/30731072/39098659-15ce64f8-4666-11e8-92cb-d378c352c792.gif)
