### ISSUE TITLE
macOS: unable to move pdf horizontally by touchpad

### ISSUE THREAD

**Issue by muzimuzhi** [texstudio-org/texstudio#1178]
### Environment
- TeXstudio: 3.0.0beta2 (haven't tested older per-release versions yet)
- Qt: Using Qt Version 5.15.0, compiled with Qt 5.15.0 R
- OS: macOS 10.15.5
- TeX distribution: texlive 2020 (irrelevant)

### Expected behavior
Use touchpad to move pdf page(s) both horizontally and vertically in internal pdf view.

### Actual behavior
After zooming in, unable to move pdf page(s) horizontally. Moving vertically works as expected.

### How to reproduce
 - In internal pdf viewer, zoom in pdf pages so that the horizontal scroll bar shows.
 - Put cursor inside pdf page area, use touchpad to move page horizontally. Page doesn't move.
 - Put cursor inside horizontal scroll bar, use touchpad to move page horizontally. Works.

**Comment by sunderme** [comment]
I don't have a mac laptop ...

**Comment by drcege** [comment]
the same issue!!

**Comment by seaneberhard** [comment]
I am seeing an especially annoying version of this bug: the pdf scrolls left but not right. (Version 3.0)

**Comment by Ukiyo-E** [comment]
the same issue!!

**Comment by boyoungzheng** [comment]
same here
TeXstudio 3.0.1 (git 3.0.1)
Using Qt Version 5.15.0, compiled with Qt 5.15.0 R
macOS 10.15.6

**Comment by dpdani** [comment]
I'm having the same issue on ArchLinux, my stats:

TeXstudio 3.0.1 (git n/a)
Using Qt Version 5.15.1, compiled with Qt 5.15.0 R

Additionally to what's been already pointed out, I've noticed that the scroll only works by moving left, i.e. regardless of my horizontal scrolling direction the viewer only scrolls to the left of the document.
This only happens rarely and mostly scrolling horizontally just plain doesn't work.
I can provide more info if you point me to related logs/configs/etc.

**Comment by netw0rkf10w** [comment]
I'm facing the same issue after upgrading!

Please consider this issue as high priority, as it reduces significantly productivity.

**Comment by netw0rkf10w** [comment]
Just for those who need it: **downgrading to 2.12.22** is the current best solution.

**Comment by nik312123** [comment]
I, too, have the same issue on TeXstudio 3.0.1. This issue did not occur on 2.12.22 for me.

I am on macOS 10.14.6.

**Comment by nik312123** [comment]
If you need to connect with someone with macOS to resolve this issue, feel free to say so below. I would be willing to help in whatever way I can.

**Comment by caglorithm** [comment]
Unfortunately, this issue still persists...

**Comment by dblaschke-LANL** [comment]
I'm seeing this same bug in Debian / Linux.

**Comment by sunderme** [comment]
probably fixed with latest commit. Please test
https://bintray.com/sunderme/texstudio/ (latest build)

**Comment by caglorithm** [comment]
> probably fixed with latest commit. Please test

Just tested. I can scroll left right but it's very buggy. Something changed obviously but I need to do 3-5 "strokes of scrolling" in order to move in the direction I intend to go. Vertical scrolling works without an issue.

**Comment by muzimuzhi** [comment]
As @caglorithm said, it partially works. Though it is still not as smooth/sensitive as in 2.12.22 or when cursor is inside the horizontal scroll bar. For example, if I swipe across the touchpad, it works to move pdf page to right most or left most. But with a minor horizontal movement, the page does not follow fingers.

**Comment by sunderme** [comment]
can you retry with the now latest build ?

**Comment by caglorithm** [comment]
> can you retry with the now latest build ?

Much better! Thanks! There is still more "friction", a bit more jittering, when scrolling horizontally vs vertically but this is much more usable than before. I would decrease the "friction" (or however it is implemented) a bit more in horizontal direction and it would be ideal.

**Comment by muzimuzhi** [comment]
> > can you retry with the now latest build ?
> 
> Much better! Thanks!

+1 Many thanks. I'm already satisfied.

**Comment by sunderme** [comment]
can you try the now latest build. Horizontal and vertical scroll should behave identical.

**Comment by nik312123** [comment]
I tested it just now (assuming it is texstudio-osx-3.0.5-202101272039-git_eac6f7d), and it worked very smoothly! Thank you very much for your work on this.

**Comment by nik312123** [comment]
Actually, I will note that zooming feels a bit jittery, but I am unsure if that is a separate issue.
