### ISSUE TITLE
V3.0.2 on MacOS bad reference to a libpoppler lib n startup

### ISSUE THREAD

**Issue by sh511** [texstudio-org/texstudio#1407]
Bad reference to libpoppler.103.dylib library on startup

Upon upgrading to version 3.0.2, error on opening TexStudio. The previous vesion on my system. 3.0.1,
is working normally.

### Environment
- TeXstudio: 3.0.2
- Qt: Version 5.15.0, compiled with Qt 5.15.0 R
- OS: MacOS Big Sur 11.1
- TeX distribution: texlive (updated 2020-12-28)

### Expected behavior
Normal start as per 3.0.1

### Actual behavior
On startup, error message about missing
/usr/local/Cellar/poppler/20.10.0/lib/libpoppler.103.dylib
(non existent on my system)
which is referenced by libpoppler-qt5.1.dylib

There is a local copy of libpoppler/103.dylib in
/Applications/texstudio.spp/Contents/Frameworks/
which should probably be referenced instead.

**Comment by muzimuzhi** [comment]
Similar problem was encountered in 3.0.0beta3 on macOS, see https://github.com/texstudio-org/texstudio/issues/1191#issuecomment-667711237. It was resolved by https://github.com/texstudio-org/texstudio/compare/e2fb1a80442aba9dcd427f37ad0a660a9eb45a60...8fa83e97b4ac113b9563123b1d311e32638fa1ac.

I think this time the problem is caused by https://github.com/texstudio-org/texstudio/commit/a8fe201dd7fe0c90cdc25a7d82ff6649dc6e49ce. In general, when texstudio is compiled on macOS with homebrew poppler, the packed `.dmg` relies on some poppler file on specific homebrew installation path.

**Comment by sunderme** [comment]
I have changed the link for osx to 3.0.1
I will give it a short try to fix but it may be that I abandon OSX builds altogether ...

**Comment by pieterjoanUvA** [comment]
same here, tried to install 'brew install poppler'
but error still persists:
 `
Process:               texstudio [874]
Path:                  /Applications/texstudio.app/Contents/MacOS/texstudio
Identifier:            texstudio
Version:               3.0.2 (0)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           texstudio [874]
User ID:               502

Date/Time:             2020-12-29 01:40:17.865 +0100
OS Version:            Mac OS X 10.15.7 (19H114)
Report Version:        12
Anonymous UUID:        A41AE5F7-92B4-903F-6CDE-9DF18BDA9A21


Time Awake Since Boot: 220 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: /usr/local/Cellar/poppler/20.10.0/lib/libpoppler.103.dylib
  Referenced from: /Applications/texstudio.app/Contents/Frameworks/libpoppler-qt5.1.dylib
  Reason: image not found

Binary Images:
       0x108233000 -        0x108e73ffb +texstudio (3.0.2 - 0) <437E506D-A0C3-38D9-AC77-313D0893E32C> /Applications/texstudio.app/Contents/MacOS/texstudio
       0x108fe6000 -        0x109025fff +libpoppler-qt5.1.dylib (0) <AA72FFA8-ECEB-3FD4-A769-A328B9253004> /Applications/texstudio.app/Contents/Frameworks/libpoppler-qt5.1.dylib
       0x10905e000 -        0x109093ff3 +org.qt-project.QtSvg (5.15 - 5.15.1) <5883587F-0A00-359F-BC7E-A6B0F16826A1> /Applications/texstudio.app/Contents/Frameworks/QtSvg.framework/Versions/5/QtSvg
       0x1090b5000 -        0x1090dffff +org.qt-project.QtPrintSupport (5.15 - 5.15.1) <5ED46A17-420B-3E36-8853-FBD0FC9C460E> /Applications/texstudio.app/Contents/Frameworks/QtPrintSupport.framework/Versions/5/QtPrintSupport
       0x109109000 -        0x109552ff7 +org.qt-project.QtWidgets (5.15 - 5.15.1) <A29125ED-5670-3BD1-8CA1-E6F221AFA04C> /Applications/texstudio.app/Contents/Frameworks/QtWidgets.framework/Versions/5/QtWidgets
       0x1096b8000 -        0x109ba6fef +org.qt-project.QtGui (5.15 - 5.15.1) <26346C32-D0E9-3183-AC50-3E8260B55520> /Applications/texstudio.app/Contents/Frameworks/QtGui.framework/Versions/5/QtGui
       0x109cc1000 -        0x109dd1ff7 +org.qt-project.QtNetwork (5.15 - 5.15.1) <6B47DC6B-2FA7-38DD-97E5-904F6BDA294E> /Applications/texstudio.app/Contents/Frameworks/QtNetwork.framework/Versions/5/QtNetwork
       0x109e20000 -        0x109e54ff3 +org.qt-project.QtXml (5.15 - 5.15.1) <F826261E-F561-3801-9FE4-1D315C5898D0> /Applications/texstudio.app/Contents/Frameworks/QtXml.framework/Versions/5/QtXml
       0x109e68000 -        0x10a01fff7 +org.qt-project.QtScript (5.15 - 5.15.1) <6DB745CD-8098-3EEA-BF53-C9DC303D3768> /Applications/texstudio.app/Contents/Frameworks/QtScript.framework/Versions/5/QtScript
       0x10a06f000 -        0x10a073fff +org.qt-project.QtConcurrent (5.15 - 5.15.1) <19385B39-9835-3B3E-9598-C6C6C42C9F7C> /Applications/texstudio.app/Contents/Frameworks/QtConcurrent.framework/Versions/5/QtConcurrent
       0x10a079000 -        0x10a5cc9f7 +org.qt-project.QtCore (5.15 - 5.15.1) <3893CD8C-1F0E-3E64-9179-C102D702DE80> /Applications/texstudio.app/Contents/Frameworks/QtCore.framework/Versions/5/QtCore
       0x10a69a000 -        0x10a719ffb +libfreetype.6.dylib (0) <860CFC10-0383-3B86-9E1C-3E5775EEC5F3> /Applications/texstudio.app/Contents/Frameworks/libfreetype.6.dylib
       0x112a41000 -        0x112ad2f47  dyld (750.6) <F58DDECD-315C-3B7C-8162-A5E8E1D62FE3> /usr/lib/dyld
    0x7fff2c3d0000 -     0x7fff2c3d4ffb  com.apple.agl (3.3.3 - AGL-3.3.3) <204E20A9-AEA9-3F9F-AE23-EECE3AFFFC54> /System/Library/Frameworks/AGL.framework/Versions/A/AGL
    0x7fff2de4e000 -     0x7fff2ec0eff2  com.apple.AppKit (6.9 - 1894.60.100) <322D043D-1140-3486-9523-3F56FF4D8349> /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
    0x7fff30bac000 -     0x7fff3102cffb  com.apple.CoreFoundation (6.9 - 1677.201) <B58E1454-15EC-3F2E-B8B6-B4F8E4DDF4A4> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
    0x7fff32f4b000 -     0x7fff32f51fff  com.apple.DiskArbitration (2.7 - 2.7) <0BBBB6A6-604D-368B-9943-50B8CE75D51D> /System/Library/Frameworks/DiskArbitration.framework/Versions/A/DiskArbitration
    0x7fff339c5000 -     0x7fff33a69ff3  com.apple.framework.IOKit (2.0.2 - 1726.140.1) <14223387-6F81-3976-8605-4BC2F253A93E> /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit
    0x7fff3614a000 -     0x7fff36214fff  com.apple.Metal (212.8 - 212.8) <98C944D6-62C8-355E-90F8-C1CA2429EF24> /System/Library/Frameworks/Metal.framework/Versions/A/Metal
    0x7fff3b755000 -     0x7fff3b764ff7  com.apple.opengl (17.10.22 - 17.10.22) <D3C57A32-6BD0-3228-B1C4-0F42A6128A6C> /System/Library/Frameworks/OpenGL.framework/Versions/A/OpenGL
    0x7fff677d0000 -     0x7fff677d2ff7  libDiagnosticMessagesClient.dylib (112) <C94F3B7B-1854-38EB-9778-834501C53B3F> /usr/lib/libDiagnosticMessagesClient.dylib
    0x7fff67ca6000 -     0x7fff67ca7fff  libSystem.B.dylib (1281.100.1) <8E6AD412-91E7-36FC-A6FD-C13B06A4952A> /usr/lib/libSystem.B.dylib
    0x7fff68022000 -     0x7fff68074fff  libc++.1.dylib (902.1) <59A8239F-C28A-3B59-B8FA-11340DC85EDC> /usr/lib/libc++.1.dylib
    0x7fff68075000 -     0x7fff6808affb  libc++abi.dylib (902) <E692F14F-C65E-303B-9921-BB7E97D77855> /usr/lib/libc++abi.dylib
    0x7fff68af5000 -     0x7fff68af7fff  libfakelink.dylib (149.1) <36146CB2-E6A5-37BB-9EE8-1B4034D8F3AD> /usr/lib/libfakelink.dylib
    0x7fff68c07000 -     0x7fff68e5efff  libicucore.A.dylib (64260.0.1) <8AC2CB07-E7E0-340D-A849-186FA1F27251> /usr/lib/libicucore.A.dylib
    0x7fff69b9b000 -     0x7fff69bcdfde  libobjc.A.dylib (787.1) <265783CE-6D74-36C9-B6D2-95D3910199EC> /usr/lib/libobjc.A.dylib
    0x7fff6a26e000 -     0x7fff6a280ff3  libz.1.dylib (76) <793D9643-CD83-3AAC-8B96-88D548FAB620> /usr/lib/libz.1.dylib
    0x7fff6ab2f000 -     0x7fff6ab34ff3  libcache.dylib (83) <AF488D13-9E89-35E0-B078-BE37CC5B8586> /usr/lib/system/libcache.dylib
    0x7fff6ab35000 -     0x7fff6ab40fff  libcommonCrypto.dylib (60165.120.1) <C7912BE5-993E-3581-B2A0-6AABDC8C5562> /usr/lib/system/libcommonCrypto.dylib
    0x7fff6ab41000 -     0x7fff6ab48fff  libcompiler_rt.dylib (101.2) <49B8F644-5705-3F16-BBE0-6FFF9B17C36E> /usr/lib/system/libcompiler_rt.dylib
    0x7fff6ab49000 -     0x7fff6ab52ff7  libcopyfile.dylib (166.40.1) <3C481225-21E7-370A-A30E-0CCFDD64A92C> /usr/lib/system/libcopyfile.dylib
    0x7fff6ab53000 -     0x7fff6abe5fdb  libcorecrypto.dylib (866.140.1) <60567BF8-80FA-359A-B2F3-A3BAEFB288FD> /usr/lib/system/libcorecrypto.dylib
    0x7fff6acf2000 -     0x7fff6ad32ff0  libdispatch.dylib (1173.100.2) <CD9C059C-91D9-30E8-8926-5B9CD0D5D4F5> /usr/lib/system/libdispatch.dylib
    0x7fff6ad33000 -     0x7fff6ad69fff  libdyld.dylib (750.6) <789A18C2-8AC7-3C88-813D-CD674376585D> /usr/lib/system/libdyld.dylib
    0x7fff6ad6a000 -     0x7fff6ad6affb  libkeymgr.dylib (30) <DB3337BE-01CA-3425-BD0C-87774FC0CDC0> /usr/lib/system/libkeymgr.dylib
    0x7fff6ad78000 -     0x7fff6ad78ff7  liblaunch.dylib (1738.140.2) <7200E214-9B4D-3B22-9844-4C7892FC890B> /usr/lib/system/liblaunch.dylib
    0x7fff6ad79000 -     0x7fff6ad7eff7  libmacho.dylib (959.0.1) <AA613A9C-961A-3B67-B696-4622FA59FC4E> /usr/lib/system/libmacho.dylib
    0x7fff6ad7f000 -     0x7fff6ad81ff3  libquarantine.dylib (110.40.3) <F234E51D-FD0B-3EE4-B679-AE3EE9C536C3> /usr/lib/system/libquarantine.dylib
    0x7fff6ad82000 -     0x7fff6ad83ff7  libremovefile.dylib (48) <7C7EFC79-BD24-33EF-B073-06AED234593E> /usr/lib/system/libremovefile.dylib
    0x7fff6ad84000 -     0x7fff6ad9bff3  libsystem_asl.dylib (377.60.2) <1563EE02-0657-3B78-99BE-A947C24122EF> /usr/lib/system/libsystem_asl.dylib
    0x7fff6ad9c000 -     0x7fff6ad9cff7  libsystem_blocks.dylib (74) <0D53847E-AF5F-3ACF-B51F-A15DEA4DEC58> /usr/lib/system/libsystem_blocks.dylib
    0x7fff6ad9d000 -     0x7fff6ae24fff  libsystem_c.dylib (1353.100.2) <BBDED5E6-A646-3EED-B33A-91E4331EA063> /usr/lib/system/libsystem_c.dylib
    0x7fff6ae25000 -     0x7fff6ae28ffb  libsystem_configuration.dylib (1061.141.1) <0EE84C33-64FD-372B-974A-AF7A136F2068> /usr/lib/system/libsystem_configuration.dylib
    0x7fff6ae29000 -     0x7fff6ae2cfff  libsystem_coreservices.dylib (114) <A199156E-058D-3ABB-BCE9-4B9F20DCED0F> /usr/lib/system/libsystem_coreservices.dylib
    0x7fff6ae2d000 -     0x7fff6ae35fff  libsystem_darwin.dylib (1353.100.2) <5B12B5DB-3F30-37C1-8ECC-49A66B1F2864> /usr/lib/system/libsystem_darwin.dylib
    0x7fff6ae36000 -     0x7fff6ae3dfff  libsystem_dnssd.dylib (1096.100.3) <EBB4C2C2-E031-3094-B40A-E67BF261D295> /usr/lib/system/libsystem_dnssd.dylib
    0x7fff6ae3e000 -     0x7fff6ae3fffb  libsystem_featureflags.dylib (17) <29FD922A-EC2C-3F25-BCCC-B58D716E60EC> /usr/lib/system/libsystem_featureflags.dylib
    0x7fff6ae40000 -     0x7fff6ae8dff7  libsystem_info.dylib (538) <8A321605-5480-330B-AF9E-64E65DE61747> /usr/lib/system/libsystem_info.dylib
    0x7fff6ae8e000 -     0x7fff6aebaff7  libsystem_kernel.dylib (6153.141.10) <FF092EE8-5BEE-3B9A-8749-F0A067115C7E> /usr/lib/system/libsystem_kernel.dylib
    0x7fff6aebb000 -     0x7fff6af06fef  libsystem_m.dylib (3178) <D1CF3A92-2424-3420-B375-DEED7AA68C53> /usr/lib/system/libsystem_m.dylib
    0x7fff6af07000 -     0x7fff6af2efff  libsystem_malloc.dylib (283.100.6) <8549294E-4C53-36EB-99F3-584A7393D8D5> /usr/lib/system/libsystem_malloc.dylib
    0x7fff6af2f000 -     0x7fff6af3cffb  libsystem_networkextension.dylib (1095.140.2) <F06C65C5-2CBE-313C-96E1-A09240F9FE57> /usr/lib/system/libsystem_networkextension.dylib
    0x7fff6af3d000 -     0x7fff6af46ff7  libsystem_notify.dylib (241.100.2) <FA22F928-D91B-3AA5-96BB-3186AC0FB264> /usr/lib/system/libsystem_notify.dylib
    0x7fff6af47000 -     0x7fff6af4ffef  libsystem_platform.dylib (220.100.1) <009A7C1F-313A-318E-B9F2-30F4C06FEA5C> /usr/lib/system/libsystem_platform.dylib
    0x7fff6af50000 -     0x7fff6af5afff  libsystem_pthread.dylib (416.100.3) <62CB1A98-0B8F-31E7-A02B-A1139927F61D> /usr/lib/system/libsystem_pthread.dylib
    0x7fff6af5b000 -     0x7fff6af5fff3  libsystem_sandbox.dylib (1217.141.2) <051C4018-4345-3034-AC98-6DE42FB8273B> /usr/lib/system/libsystem_sandbox.dylib
    0x7fff6af60000 -     0x7fff6af62fff  libsystem_secinit.dylib (62.100.2) <F80872AA-E1FD-3D7E-8729-467656EC6561> /usr/lib/system/libsystem_secinit.dylib
    0x7fff6af63000 -     0x7fff6af6affb  libsystem_symptoms.dylib (1238.120.2) <702D0910-5C34-3D43-9631-8BD215DE4FE1> /usr/lib/system/libsystem_symptoms.dylib
    0x7fff6af6b000 -     0x7fff6af81ff2  libsystem_trace.dylib (1147.120.1) <BC141783-66D9-3137-A783-211B38E49ADB> /usr/lib/system/libsystem_trace.dylib
    0x7fff6af83000 -     0x7fff6af88ff7  libunwind.dylib (35.4) <42B7B509-BAFE-365B-893A-72414C92F5BF> /usr/lib/system/libunwind.dylib
    0x7fff6af89000 -     0x7fff6afbeffe  libxpc.dylib (1738.140.2) <54EEF402-42C7-3995-BADE-93C48EFC4452> /usr/lib/system/libxpc.dylib

Model: MacBookPro9,1, BootROM 233.0.0.0.0, 4 processors, Quad-Core Intel Core i7, 2,6 GHz, 16 GB, SMC 2.1f175
Graphics: kHW_IntelHD4000Item, Intel HD Graphics 4000, spdisplays_builtin
Graphics: kHW_NVidiaGeForceGT650MItem, NVIDIA GeForce GT 650M, spdisplays_pcie_device, 1 GB
Memory Module: BANK 0/DIMM0, 8 GB, DDR3, 1600 MHz, 0x029E, 0x434D5358384758334D314131363030433130
Memory Module: BANK 1/DIMM0, 8 GB, DDR3, 1600 MHz, 0x029E, 0x434D5358384758334D314131363030433130
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0xF5), Broadcom BCM43xx 1.0 (7.21.190.33 AirPortDriverBrcm4360-1601.1)
Bluetooth: Version 7.0.6f8, 3 services, 18 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en1
Serial ATA Device: WDC WDS100T1B0A-00H9H0, 1 TB
Serial ATA Device: HL-DT-ST DVDRW  GS31N
USB Device: USB 3.0 Bus
USB Device: USB 2.0 Bus
USB Device: Hub
USB Device: FaceTime HD Camera (Built-in)
USB Device: USB 2.0 Bus
USB Device: Hub
USB Device: Hub
USB Device: Apple Internal Keyboard / Trackpad
USB Device: IR Receiver
USB Device: BRCM20702 Hub
USB Device: Bluetooth USB Host Controller
Thunderbolt Bus: MacBook Pro, Apple Inc., 25.1

`

**Comment by DevDavido** [comment]
I have the exact same error like @pieterjoanUvA since 3.0.2:
```
Process:               texstudio [806]
Path:                  /Users/xxx/Desktop/texstudio.app/Contents/MacOS/texstudio
Identifier:            texstudio
Version:               3.0.2 (0)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           texstudio [806]
User ID:               501

Date/Time:             2020-12-29 13:32:22.374 +0100
OS Version:            Mac OS X 10.15.7 (19H114)
Report Version:        12
Anonymous UUID:        2611D1BA-741A-685A-C70D-3808D253A5CF


Time Awake Since Boot: 540 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: /usr/local/Cellar/poppler/20.10.0/lib/libpoppler.103.dylib
  Referenced from: /Users/xxx/Desktop/texstudio.app/Contents/Frameworks/libpoppler-qt5.1.dylib
  Reason: image not found
[...]
```

**Comment by sunderme** [comment]
brew has meanwhile updated to a new version of popper ...

**Comment by sunderme** [comment]
can you try https://github.com/texstudio-org/texstudio/releases/download/3.0.3/texstudio-3.0.3-osx.dmg

**Comment by DevDavido** [comment]
No more errors for me with this 3.0.3 release @sunderme 👍

**Comment by sh511** [comment]
3.0.3 works like a charm here too, thanks !!!   8-)

**Comment by sunderme** [comment]
fixed with 3.0.3

**Comment by pieterjoanUvA** [comment]
Thanks for the fix, works also for me.
