### ISSUE TITLE
Please test txs 4.0.0alpha7 on OSX

### ISSUE THREAD

**Issue by sunderme** [texstudio-org/texstudio#1700]
This bundle should work (hopefully)

**Comment by muzimuzhi** [comment]
It now opens properly. I'll test more tomorrow.

**Comment by sunderme** [comment]
thanks

**Comment by muzimuzhi** [comment]
I encountered the same issue reported in #1635.

After deleting `texstudio.ini` then opening 4.0.0alpha7, "Help -> Check LaTeX Installation" shows
```
Environment variables:
[...]
PATH=:/usr/local/texlive/2012/bin/x86_64-darwin

Command configuration in TeXstudio:
    [...]
    PdfLaTeX (pdflatex) (r): /Library/TeX/texbin/pdflatex -synctex=1 
```

While with 4.0.0alpha5, `PATH` is longer and the txs command does not contain full path:
```
Environment variables:
[...]
PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/opt/X11/bin:/usr/local/texlive/2012/bin/x86_64-darwin

Command configuration in TeXstudio:
    [...]
    PdfLaTeX (pdflatex) (r): pdflatex -synctex=1 -interaction=nonstopmode %.tex
```
According to https://scriptingosx.com/2017/05/where-paths-come-from/ (I learnt it in https://github.com/texstudio-org/texstudio/issues/768#issuecomment-555701552), those parts missing in 4.0.0alpha7's `PATH` (`/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/opt/X11/bin`) are added by executing `/etc/profile`. Among the missing parts, `/Library/TeX/texbin:/opt/X11/bin`, stored in file `/etc/paths.d/TeX`, is what texstudio need.

**Comment by sunderme** [comment]
the path in the checkLatex-function is incomplete as it only uses the printEnv command.
Did you experience failed execution of commands ?

**Comment by sunderme** [comment]
should be resolved

**Comment by muzimuzhi** [comment]
> should be resolved

Tested the CD artifact for https://github.com/texstudio-org/texstudio/commit/ea999184b643d64f7a7bd47e82259f2df88bed8d, yes it's resolved. Thanks.

**Comment by muzimuzhi** [comment]
Another one: Character rendering seems to be affected by whether the background color is applied. Look at the words "every node" in the following screen recording.

https://user-images.githubusercontent.com/6376638/126898405-35d5e86f-140a-4c23-9283-065f8468137f.mov

**Comment by muzimuzhi** [comment]
Last opened documents wont't open automatically.

Version: git 4.0.0alpha7-19-gea999184

Steps to reproduce:
 - Open texstudio, open several tex files, then close texstudio
 - Check that the `Files\Last%20Document` line in `~/.config/<username>/texstudio.ini` is not updated (even with a fresh `.ini`)
   - That line will include at most one file path.
 - Reopen texstudio, no tex file opens automatically, a pdf file corresponding to the only one tex file recorded in `Files\Last%20Document` opens in the internal pdf viewer.

**Comment by muzimuzhi** [comment]
I tried to open texstudio from command line, and may have found something useful.

With 4.0.0alpha7-19-gea999184 and `texstudio.ini` deleted, opening txs from command line produces
```
$ ~ /Applications/texstudio.app/Contents/MacOS/texstudio ; exit;
QPainter::begin: Paint device returned engine == 0, type: 2
QPainter::translate: Painter not active
QPainter::rotate: Painter not active
QPainter::begin: Paint device returned engine == 0, type: 2
QPainter::translate: Painter not active
QPainter::rotate: Painter not active
qt.qpa.fonts: Populating font family aliases took 505 ms. Replace uses of missing font family "Monospace" with one that exists to avoid this cost. 
qt.core.qobject.connect: QObject::connect: Cannot queue arguments of type 'const void*'
(Make sure 'const void*' is registered using qRegisterMetaType().)
qt.core.qobject.connect: QObject::connect: No such signal QButtonGroup::buttonClicked(int)
"4.0.0" "alpha"
"4.0.0" "alpha"
"4.0.0" "alpha"
"4.0.0" "alpha"
"4.0.0" "alpha"
"4.0.0" "alpha"
"4.0.0" "alpha"
"3.1.2" ""
```
Lines except for the `qt.qpa.fonts` one and version info ones are not seen before, e.g. with 4.0.0alpha5. Also, each time a tex is opened from command line, the following message is written.
```
qt.core.qobject.connect: QObject::connect: Cannot queue arguments of type 'const void*'
(Make sure 'const void*' is registered using qRegisterMetaType().)
```

**Comment by sunderme** [comment]
> Last opened documents wont't open automatically.
> 
> Version: git 4.0.0alpha7-19-gea999184
> 
> Steps to reproduce:
> 
>     * Open texstudio, open several tex files, then close texstudio
> 
>     * Check that the `Files\Last%20Document` line in `~/.config/<username>/texstudio.ini` is not updated (even with a fresh `.ini`)
>       
>       * That line will include at most one file path.
> 
>     * Reopen texstudio, no tex file opens automatically, a pdf file corresponding to the only one tex file recorded in `Files\Last%20Document` opens in the internal pdf viewer.

Do you still see the issue after having deleted texstudio.ini ?
Looks okay on linux.

**Comment by muzimuzhi** [comment]
> Do you still see the issue after having deleted texstudio.ini ?

Yes.

**Comment by sunderme** [comment]
looks like the character width issue is fixed

**Comment by muzimuzhi** [comment]
Tested with https://github.com/texstudio-org/texstudio/commit/5efba2742f03dd1430ce591a74bbad7ab2557616 ([artifacts](https://github.com/texstudio-org/texstudio/actions/runs/1084837366)), problem remained. Waiting for the build for latest commit.

Also, it is tested on an 1920x1080 pixels external screen, not so hidpi? Though the problem remains in built-in retina screen.

**Comment by sunderme** [comment]
@muzimuzhi I don't see any issue with texstudio.ini/session restoration on mac either.
My guess is that txs crashes on quitting. Can you run a debugger on txs ?

**Comment by muzimuzhi** [comment]
> Can you run a debugger on txs ?

I'm willing to do, but how? Do you mean the Qt debugger https://doc.qt.io/qtcreator/creator-debugger-operating-modes.html?

**Comment by sunderme** [comment]
qtdebugger is the simplest one

**Comment by sunderme** [comment]
@muzimuzhi do you still have the issue with storing open documents ?

**Comment by muzimuzhi** [comment]
Yes that problem persists with 4.0.0alpha8. So sorry I was a bit lazy to learn and use qt-creator. I will try (again) this weekend.

**Comment by sunderme** [comment]
alternative approach, are any other configs stored/changed permanently ?

**Comment by muzimuzhi** [comment]
The answer seems to be yes. Tested with changing General - Appearance - Font size, Build - Meta Commands - Default Compiler, Menus - Insert New Menu Item, and Completion - Permanently Active Completion files, each of them is stored.

**Comment by XX4869** [comment]
> Last opened documents wont't open automatically.
> 
> Version: git 4.0.0alpha7-19-gea999184
> 
> Steps to reproduce:
> 
> * Open texstudio, open several tex files, then close texstudio
> * Check that the `Files\Last%20Document` line in `~/.config/<username>/texstudio.ini` is not updated (even with a fresh `.ini`)
>   
>   * That line will include at most one file path.
> * Reopen texstudio, no tex file opens automatically, a pdf file corresponding to the only one tex file recorded in `Files\Last%20Document` opens in the internal pdf viewer.

Hi, did you figure out how to resolve this issue? I am having the exact same issue on my Macs. TexStudio only reopens the last PDF file on the right and the left panel is empty. The lastsession.txss file only stores the pdf information with no tex file information. Tried to delete the texstudio.ini file but it didn't help. Thanks.
