### ISSUE TITLE
TexStudio 4.0.0 MacOS does not reopen tex files from last session

### ISSUE THREAD

**Issue by XX4869** [texstudio-org/texstudio#1797]
After updating to 4.0.0 on my Macs, TexStudio does not open tex files from previous session on startup. I found
[this post](https://github.com/texstudio-org/texstudio/issues/1700#issuecomment-886597260) that describes exactly the same issue as I am having but unfortunately that thread is closed with no solution given... Does anyone have experienced this issue or have any idea on how to solve it? Thanks.

Environment
- TeXstudio:  4.0.0
- Qt: 6.1.3
- OS:  Mac

### Expected behavior
TexStudio should reopen all opened tex files from last session.

### Actual behavior
On startup, TexStudio does not open any tex files that were previously opened. Only the last viewed PDF will open on the right (if there was a pdf opened).

**Comment by sunderme** [comment]
I have checked on two macs and it has worked fine.
Maybe file names ? Access rights on your mac ?
Without further hints, there is nothing I can do.

**Comment by XX4869** [comment]
The issue (I think) is that, when I close the TexStudio, it doesn't write into lastsession.txss file properly---it looks like this

InternalPDFViewer]
Embedded=true
File=SOME PDF

[Session]
Bookmarks=@Invalid()
CurrentFile=
FileVersion=1
MasterFile=

Any idea on what's happening with that file? I notice that you mentioned in the other thread that it maybe because TexStudio crashes at closing so the last session didn't get stored, but I don't know how to check that...

**Comment by sunderme** [comment]
maybe removing lastSession completely ?

**Comment by XX4869** [comment]
I have tried removing lastsession.txss, as well as removing texstudio.ini. None of them works.

**Comment by sunderme** [comment]
have you tried simple filenames ?

**Comment by XX4869** [comment]
What do you mean? Simple tex file name such as 123.tex? Or simple file path?

**Comment by XX4869** [comment]
Basically, if I open a tex file with its pdf in TexStudio 3.1.2 and close the app, the lastSession.txss is saved properly with the correct tex file names, etc. Something like this

InternalPDFViewer]
Embedded=true
File=SOME PDF

[Session]
Bookmarks=@Invalid()
CurrentFile=SOME TEX FILE
File0\Col=0
File0\EditorGroup=0
File0\FileName=SOME TEX FILE
File0\FirstLine=0
File0\FoldedLines=
File0\Line=0
FileVersion=1
MasterFile=

But if I do the same thing in TexStudio 4.0.0, the lastSession.txss will not properly saved.

**Comment by sunderme** [comment]
what happens if you use file/sessions.../save ?

**Comment by XX4869** [comment]
If I save the session to somewhere else (e.g., desktop) and load it, everything works fine---I get what I had before closing TexStudio. 
But if I save the session as lastSession.txss (replace it) in the texstudio configuration folder, it saves properly BUT it gets replaced as empty file again as soon as I close the app---so reopen TexStudio gets me empty workspace.

Again, what's strange to me is that 3.1.2 still works fine (I reinstalled 3.1.2 after this issue and keep them both on my Mac now), and I believe the two versions retrieve/save the lastSession.txss file at the same location.

**Comment by netw0rkf10w** [comment]
I confirm this issue on macOS 10.15.7 Catalina.

**Comment by sunderme** [comment]
Can you try to disable Option/Sessions/Store relative paths ?
<img width="966" alt="grafik" src="https://user-images.githubusercontent.com/14033169/136066347-e3659569-fac9-4b8e-8d21-1299124209d9.png">

**Comment by XX4869** [comment]
Just tried. No, it doesn't work.

I don't think the issue is due to the path. Because the last opened PDF is correctly saved and will open after restarting the app. It is just all the opened tex files that aren't saved into the lastSession.txss file.

**Comment by sunderme** [comment]
please try https://github.com/texstudio-org/texstudio/suites/3964516450/artifacts/99626278 preferably from command line (open texstudio.app).

**Comment by XX4869** [comment]
No, this 4.0.1 doesn't fix the issue. Only the PDF will open, no tex files on the left. 

lastSession has always been writable, and that's how the last opened PDF is saved. But it doesn't write any tex files.

**Comment by sunderme** [comment]
can you run it on commandline and report the debug output ?

**Comment by sunderme** [comment]
put the texstudio.app in a known folder (Documents)
open the command line, change to that folder via "cd <subfolder>" see google
start texstudio with ```open texstudio.app```

**Comment by XX4869** [comment]
Okay. The app opens, and that's it. I see nothing in the terminal.

**Comment by sunderme** [comment]
ah yes, probably my fault.
I will try again the coming days.

**Comment by aiMojica10** [comment]
I had the same issue, but every time I closed TexStudio, a pop-up message appeared indicating that it couldn't save the lastSession.txss.  So, I:
 * Searched this file  (lastSession.txss) in finder, I realized that the config folder did not exist
 * So I created the config folder, then I opened TexStudio again and closed it. After that, everything worked fine

**Comment by XX4869** [comment]
Well, at least in my case (two Macs), the config folder and lasSession.txss both exist. And TexStudio can write the opened pdf file into lasSession.txss properly upon closing, but it couldn't write any opened tex files into lasSession.txss.

**Comment by sunderme** [comment]
possibly fixed with latest dev build, please check !
https://github.com/texstudio-org/texstudio/actions/runs/1429248545

**Comment by XX4869** [comment]
I tested 4.0.4 on one of my Mac and and the issue is still there---no auto save of opened tex files upon closing the app.

**Comment by anisiobraga** [comment]
I've also just tested version 4.0.4 and the issue persists! How I miss the previous session.(:-/  
By the way,I'm using MacOs Big Sur 11.6.1

**Comment by 31PNMR** [comment]
TeXstudio 4.0.4 (qt 6.2.1) on macOS 12.0.1 still has the issue. I don't know if this has anything to do with it, but I always mention it because sometimes it is the source of the problem, but my OS language is not en_US, but ja_JP.

**Comment by anisiobraga** [comment]
> > I've also just tested version 4.0.4 and the issue persists! How I miss the previous session.(:-/ By the way,I'm using MacOs Big Sur 11.6.1
> 
> qt5 version ?

TeXstudio 4.0.4 (git 4.0.4)
Using Qt Version 6.2.1, compiled with Qt 6.2.1 R

This version has not fixed "restoring last session"as it is stated in the change log. I've always updated without removing previous version. Is there any suggestion as how to proceed with the installation and configuration in order to get restoring last session to work?

**Comment by muzimuzhi** [comment]
> Is there any suggestion as how to proceed with the installation and configuration in order to get restoring last session to work?

for now, use the Qt5 version

**Comment by anisiobraga** [comment]
> > Is there any suggestion as how to proceed with the installation and configuration in order to get restoring last session to work?
> 
> for now, use the Qt5 version

Thanks! It's works with QT5 version. 
By the way, I've just realized there are two versions TeXstudio 4.0.4. A link for the one compiled with QT5 is only at the bottom page. Since this is the one that works, it should be the one in the main download icon.

**Comment by sunderme** [comment]
I have bitten the bullet and implemented a new session restore file format.
Please test the latest dev build (currently building)

**Comment by chchen2021** [comment]
I downloaded the latest [dev build](https://github.com/texstudio-org/texstudio/actions/runs/1429248545) on macOS Monterey, but the automatic restoration of previous session is still not working, so changing over to TeXstudio 4.0.4 QT5 which works just like version 3.

**Comment by sunderme** [comment]
it should work in the second start when txs can write the session in the new format.

**Comment by chchen2021** [comment]
Just reinstalled the development version, and restarted Texstudio at least three times. It does not work. Only the pdf file location gets written to the .txss file.

**Comment by sunderme** [comment]
there should be a txss2 file ?

**Comment by sunderme** [comment]
you have downloaded an old version
https://github.com/texstudio-org/texstudio/actions/runs/1454351902

**Comment by sunderme** [comment]
latest means looking here: https://github.com/texstudio-org/texstudio/actions/workflows/cd.yml

**Comment by chchen2021** [comment]
this time there is a txss2 file, but again only pdf is written there. I am going to revert back to the QT5 for now.

**Comment by sunderme** [comment]
I can't fix it as I don't see the issue.
Qt5 is officially unsupported on OSX 12, so ...

**Comment by XX4869** [comment]
Can confirm that the issue is still there on two Macs (including a brand new MacBook). They are both running OSX 12.0.1. The TexStudio version is:
TeXstudio 4.1.0 (git 4.0.4-16-ge9cfcec7)
Using Qt Version 6.2.1, compiled with Qt 6.2.1 R.

> this time there is a txss2 file, but again only pdf is written there. I am going to revert back to the QT5 for now.
As mentioned above, I am seeing the same txss2 file with only pdf file path saved in it.

**Comment by Argon-** [comment]
Maybe this helps (because it was asked for but never provided): the linked dev version (4.1.0) above works for me but only once.

For the sake of completeness two logs:
I removed lastSession.txss, opened TexStudio and a file and closed it again. I omitted the log upon reopening TexStudio again because it is identical to the first one. (Is there a `-v`/verbose flag?)
I made sure that the file path contains no spaces nor non-ASCII characters, just in case.
macOS BigSur, TexStudio 4.0.4, Qt 6.

    Julian texstudio → rm lastSession.txss
    Julian texstudio → /Applications/texstudio.app/Contents/MacOS/texstudio
    QPainter::begin: Paint device returned engine == 0, type: 2
    QPainter::translate: Painter not active
    QPainter::rotate: Painter not active
    QPainter::begin: Paint device returned engine == 0, type: 2
    QPainter::translate: Painter not active
    QPainter::rotate: Painter not active
    qt.qpa.fonts: Populating font family aliases took 921 ms. Replace uses of missing font family ".SF NS Text" with one that exists to avoid this cost.
    lastSession filename: "/Users/Julian/.config/texstudio/lastSession.txss"
    current file: "/Users/Julian/Documents/Uni/x/paper-de-default-listings-cleveref.tex"
    lastSession filename: "/Users/Julian/.config/texstudio/lastSession.txss"
    current file: ""
    Julian texstudio → cat lastSession.txss
    [InternalPDFViewer]
    Embedded=false
    File=
    
    [Session]
    Bookmarks=@Invalid()
    CurrentFile=
    FileVersion=1
    MasterFile=


macOS BigSur, TexStudio 4.0.4 (git 4.0.4-16-ge9cfcec7), Qt 6.

    Julian texstudio → /Applications/texstudio-dev.app/Contents/MacOS/texstudio
    QPainter::begin: Paint device returned engine == 0, type: 2
    QPainter::translate: Painter not active
    QPainter::rotate: Painter not active
    QPainter::begin: Paint device returned engine == 0, type: 2
    QPainter::translate: Painter not active
    QPainter::rotate: Painter not active
    qt.qpa.fonts: Populating font family aliases took 692 ms. Replace uses of missing font family ".SF NS Text" with one that exists to avoid this cost.
    Julian texstudio → cat lastSession.txss2
    {
        "InternalPDFViewer": {
            "Embedded": false,
            "File": ""
        },
        "Session": {
            "Bookmarks": [
            ],
            "CurrentFile": "../../Documents/Uni/x/paper-de-default-listings-cleveref.tex",
            "FileVersion": 1,
            "Files": [
                {
                    "Col": 0,
                    "EditorGroup": 0,
                    "FileName": "../../Documents/Uni/x/paper-de-default-listings-cleveref.tex",
                    "FirstLine": 42,
                    "FoldedLines": "",
                    "Line": 0
                }
            ],
            "MasterFile": ""
        }
    }

Now I wanted to try spaces in the file name and renamed a directory. Naturally, it didn't restore (because the file no longer existed), however, even after multiple iterations of open->close->... lastSession.txss2 was never populated with file paths again. I even removed the spaces from the directory again but still no luck.
(Log same as above)

    cat lastSession.txss2
    {
        "InternalPDFViewer": {
            "Embedded": false,
            "File": ""
        },
        "Session": {
            "Bookmarks": [
            ],
            "CurrentFile": "",
            "FileVersion": 1,
            "Files": [
            ],
            "MasterFile": ""
        }
    }

**Comment by Argon-** [comment]
Found the problem! It's probably simpler than what you expected.
When I close TexStudio with the window close indicator (red x bubble, window decoration) it works. When I close through "Quit" (cmd+Q) it doesn't. So I assume the session storage handler is simply not connected to this kind of close event. :)

**Comment by tweh** [comment]
Well actually the read button in macOS should only close a window but not quit the app. This is at least the case for native apps and I think it was the case for TeXstudio as well but I’m not sure if this changed or if I can’t remember correctly.

**Comment by Argon-** [comment]
It definitely closes for me, at least now.
I also don't think the "read button in macOS should only close a window" Apple guideline is up-to-date anymore. This used to be a rule in earlier days but nowadays even Apple themselves regularly violate it with their own system apps (e.g. Reminders.app closes, Calendar.app doesn't). In cases where an app only has one window it's "ok" for the red button to close the whole program for quite some time now.

**Comment by sunderme** [comment]
the reproducible steps helped to find the issue, thanks.

**Comment by XX4869** [comment]
> the reproducible steps helped to find the issue, thanks.

Does 4.1.1 fix this or the next release? I still have the issue with 4.1.1.

**Comment by muzimuzhi** [comment]
@XX4869 The next release (probably 4.1.2). You can try the build here: https://github.com/texstudio-org/texstudio/actions/runs/1491590612.

**Comment by XX4869** [comment]
Got it. Thanks!!
