### ISSUE TITLE
Autocomplete and syntax highlight for classes and packages lost after update some MikTeX packages

### ISSUE THREAD

**Issue by fernandozucatelli** [texstudio-org/texstudio#2218]
### Environment
- TeXstudio: 3.1.2 (and also 4.2.2)
- Qt: Using Qt Version 5.15.2, compiled with Qt 5.15.2 R
- OS: Windows 10
- TeX distribution: MikTeX 22.3

### Expected behavior

Autocomplete and syntax highlight working as previously and as it works for other commands.

![image](https://user-images.githubusercontent.com/2475760/162102055-1913c010-b628-4669-8e72-e53d50a57e14.png)

### Actual behavior

There is no autocomplete for classes, they are not highlight (default green).

![image](https://user-images.githubusercontent.com/2475760/162101465-409609b2-aa8f-4a3b-a5b2-95090fb9b983.png)

Same is true for packages.

![image](https://user-images.githubusercontent.com/2475760/162101627-7e278dca-0483-4e2f-81ef-6e822a348f59.png)

### Related issues and what I've tried

After updating some packages through MikTeX my TeXstudio lost the ability to show the autocomplete list and highlight for classes and packages, but not for environments and macros.

I found two other similar closed issues, but I could not understand what solved their problems, specially the one in Linux.

 1. https://github.com/texstudio-org/texstudio/issues/1975
 2. https://github.com/texstudio-org/texstudio/issues/2178

I know where to find the `.dat`-files packageCache and miktexPackageNames, but no `.profile`. I also don't know how to use `PATH`, `MANPATH `and `INFOPATH`, cited in one comment from [issue 1975](https://github.com/texstudio-org/texstudio/issues/1975), if they are applied to Windows.

![image](https://user-images.githubusercontent.com/2475760/162104606-1393a9aa-0324-44a1-888f-c13175c7e420.png)

### Install and uninstall

I uninstalled version 3.1.2 and installed 4.2.2. No effect.
I downgraded back to 3.1.2. The issue persisted.

I still have not tried to uninstall and reinstall MikTeX.

**Comment by octaeder** [comment]
I checked development version texstudio-win-qt6-4.2.3-202204051806-git_8582ee2.exe (Win10, MikTex):

![grafik](https://user-images.githubusercontent.com/102688820/162136388-42f3b9e5-2aed-4213-abc2-4739255ae913.png)
So colouring seems to be ok.

![grafik](https://user-images.githubusercontent.com/102688820/162136465-06acbd72-17d1-4f91-a0d2-5e8e09ed0c35.png)
Autocompl. for packacke ok.

![grafik](https://user-images.githubusercontent.com/102688820/162136566-a763ad0b-138d-487d-b5fb-3dc39e872f17.png)
Autocompl. for classes not ok.

Above version about 2 days old.

**Comment by sunderme** [comment]
the issue was fixed for #2178 
class completion has not been implemented.

**Comment by fernandozucatelli** [comment]
Indeed, it is my mistake about autocomplete for classes. But it is still not highlighting syntax (green) for classes and both issues for packages.

Are you implying something like this?
 - If after updating some package in MikTeX and having this issue, then you should download the newest TeXstudio version.

**Comment by sunderme** [comment]
yes, the implication already by @octaeder is, that current release does not handle the changed format of miktex (hence the issues you see), but the next release will fix the issue. If you are curious, you can download and use a development version of texstudio which has the issue fixed, see webpage.

**Comment by fernandozucatelli** [comment]
Understood.

So while I wait for the official release of TeXstudio version 4.2.3, I just downgraded my MikTeX to version 2.9.7015 (the one I keep at my hard disk for these kind of issues).

Syntax highlight for both classes and packages and autocomplete for packages are working once again.

![image](https://user-images.githubusercontent.com/2475760/162297565-57811e7c-41b2-44bd-972d-d77680e202bd.png)

**Comment by fernandozucatelli** [comment]
Note: I download version 4.2.3 and the autocomplete function is working.
