### ISSUE TITLE
Syntax highlighting with lstlisting causes all following text to be green

### ISSUE THREAD

**Issue by jeffspieg** [texstudio-org/texstudio#3762]
### Environment
- TeXstudio: < 4.8.0	-->
- Qt: 
- OS: 
- TeX distribution: 

### Expected behavior
Syntax highlighting would work for lstlisting

### Actual behavior
![image](https://github.com/user-attachments/assets/272b4ccf-dea3-4a3d-bb4c-64f24c8e2620)

### How to reproduce
It seems to just happen with lstlisting as shown in the picture.  If i select and hit Ctrl-T twice it fixes the problem, but it  reoccurs frequently.

**Comment by muzimuzhi** [comment]
Tried with a minimal example in TeXstudio 4.8.2alpha1, not reproducible. Maybe that's already fixed between 4.8.0 and 4.8.2alpha1, or my example is too minimal.

```tex
\documentclass{article}
\usepackage{listings}

\begin{document}
content

\begin{lstlisting}[]
code code
\end{lstlisting}

abc abc
\end{document}
```

**Comment by octaeder** [comment]
TeXstudio 4.8.0 (git 4.8.0)
Using Qt Version 6.7.0, compiled with Qt 6.7.0 R

![image](https://github.com/user-attachments/assets/65929ebb-ae44-45e8-8f22-70209f96eaf0)

**Comment by mbertucci47** [comment]
I can't reproduce at the moment, but I will add that this happens to me frequently as well with verbatim environments (`#V` classifier in cwl). Deleting some text like a character of the env name and re-typing it usually fixes it.

**Comment by sunderme** [comment]
I would need some minimal example.

**Comment by jeffspieg** [comment]
Here is a minimal example from Texstudio green lstlisting bug.tex

\input{../Autotestcon/preamble}
\RCRtrue

\input{../Autotestcon/documentclass}

\printtrue

\input{../Autotestcon/pkg}


\begin{document}
	\bibliographystyle{IEEEtran}
	%
	% paper title
	% can use linebreaks \\ within to get better formatting as desired
	% make the title area
	\title{Texstudio green bug}
	\maketitle
	

	\subsubsection{Introduction}
	
	Dynamic counters are important to prevent end row or column counting.
	
	\begin{lstlisting}[
		caption={Dynamic counter of SQL pulled data column}, label=Dynamic counter of SQL data column, 
		linewidth=\columnwidth, breaklines=true, 
		language=Excel]
		=UNIQUE(
		FILTER(
		INDIRECT("DR!" & CHAR(64 + MATCH(D3, DR!$2:$2, 0)) & "$3:" & CHAR(64 + MATCH(D3, DR!$2:$2, 0)) & ROW(INDEX(DR!$A:$A, 'Par1'!$N$1))),
		(INDIRECT("DR!" & CHAR(64 + MATCH("D Component", DR!$2:$2, 0)) & "$3:" & CHAR(64 + MATCH("D Component", DR!$2:$2, 0)) & ROW(INDEX(DR!$A:$A, 'Par1'!$N$1))) <>
		INDIRECT("DR!" & CHAR(64 + MATCH("Material #", DR!$2:$2, 0)) & "$3:" & CHAR(64 + MATCH("Material #", DR!$2:$2, 0)) & ROW(INDEX(DR!$A:$A,'Par1'!$N$1))))
		)
		)
	\end{lstlisting}
	
	Looking at Listing~\ref{Dynamic counter of SQL data column} we see a complex combination of functions that aims to filter and extract unique values from a dynamically defined range in the \texttt{DR} sheet, based on multiple conditions. Here’s a detailed breakdown of the formula.
	
	\subsubsection{Explanation}
	
	\begin{enumerate}
		\item \textbf{MATCH(D3, DR!\$2:\$2, 0)}:
		\begin{itemize}
			\item Finds the column number in the \texttt{DR} sheet where the header matches the value in cell \texttt{D3}.
		\end{itemize}
		
		\item \textbf{CHAR(64 + MATCH(D3, DR!\$2:\$2, 0))}:
		\begin{itemize}
			\item Converts the column number to a corresponding letter (e.g., 1 becomes A, 2 becomes B).
		\end{itemize}
		
		\item \textbf{INDIRECT(``DR!" \& CHAR(64 + MATCH(D3, DR!\$2:\$2, 0)) \& ``\$3:" \& CHAR(64 + MATCH(D3, DR!\$2:2, 0)) \& ROW(INDEX(DR!\$A:\$A, 'Par1'!\$N\$1)))}:
		\begin{itemize}
			\item Constructs a range reference in the \texttt{DR} sheet starting from row 3 to the row number specified in \texttt{'Par1'!\$N\$1} for the column found in the previous step.
			\item This INDIRECT function dynamically constructs a range to be used in the FILTER function.
		\end{itemize}
		
		\item \textbf{FILTER(..., (Condition))}:
		\begin{itemize}
			\item Filters the range defined by the INDIRECT function based on a condition.
		\end{itemize}
		
		\item \textbf{Condition}:
		\begin{itemize}
			\item \texttt{(INDIRECT("DR!" \& CHAR(64 + MATCH("D Component", DR!\$2:\$2, 0)) \& "\$3:" \& CHAR(64 + MATCH("D Component", DR!\$2:\$2, 0)) \& ROW(INDEX(DR!\$A:\$A, 'Par1'!\$N\$1))) <> INDIRECT("DR!" \& CHAR(64 + MATCH("Material \#", DR!\$2:\$2, 0)) \& "\$3:" \& CHAR(64 + MATCH("Material \#", DR!\$2:\$2, 0)) \& ROW(INDEX(DR!\$A:\$A,'Par1'!\$N\$1))))}:
			\begin{itemize}
				\item Constructs two additional ranges for columns where the headers are ``D Component" and ``Material \#" respectively.
				\item Compares the values in these columns row by row.
				\item The condition checks where the value in the ``D Component" column is not equal to the value in the ``Material \#" column.
			\end{itemize}
		\end{itemize}
		
		\item \textbf{UNIQUE(...)}:
		\begin{itemize}
			\item Extracts unique values from the filtered results to ensure there are no duplicates.
		\end{itemize}
	\end{enumerate}
	
	\subsubsection{Summary}
	
	\begin{itemize}
		\item The formula dynamically references columns in the \texttt{DR} sheet based on the headers specified in cell \texttt{D3}, "D Component", and "Material \#".
		\item It creates ranges starting from row 3 to a row number defined in \texttt{'Par1'!$N$1}.
		\item It filters the values in the dynamically referenced column (from \texttt{D3}) where the value in the "D Component" column is not equal to the value in the "Material \#" column.
		\item Finally, it returns a list of unique values that meet these conditions.
	\end{itemize}
	
	This formula is quite powerful and flexible, allowing dynamic column and row referencing, filtering based on complex conditions, and ensuring the results are unique.
	
	\begin{thebibliography}{9}
		\bibitem{excel_office}
		Microsoft Office Support, \emph{Excel Functions}, Available at: \url{https://support.microsoft.com/excel}
	\end{thebibliography}
	
	
	\subsection{Improving the count}
	
	
	\begin{lstlisting}[
		caption={Counts occurrences of values in a specified range, excluding rows where the ``Material" column has the same value}, label=Counts occurrences of values in a specified range,
		linewidth=\columnwidth, breaklines=true, 
		language=Excel]
		=LET(
		fColumn, D4:INDEX(D:D, D2 - 2),
		dataColIndex, MATCH(D3, DR!$2:$2, 0),
		matColIndex, MATCH("Material #", DR!$2:$2, 0),
		dataRange, INDIRECT("DR!" & CHAR(64 + dataColIndex) & "3:" & CHAR(64 + dataColIndex) & $N$1),
		matRange, INDIRECT("DR!" & CHAR(64 + matColIndex) & "3:" & CHAR(64 + matColIndex) & $N$1),
		counts, MAP(
		fColumn,
		LAMBDA(fValue,
		SUM((dataRange = fValue) * (matRange <> fValue))
		)
		),
		IFERROR(counts, "No Matches")
		)	
	\end{lstlisting} 
	
	This code uses Excel's `LET`, `MATCH`, `INDIRECT`, `MAP`, `LAMBDA`, and `IFERROR` functions to dynamically calculate counts of values in a specified range based on certain conditions. Here's a step-by-step breakdown of what the code does:

	
	\section{Excel Dynamic Arrays}
	Provide this answer in latex source at the subsubsection level for titles with enumerations and itemizations as shown (no latex headers needed, but you should include the intro and conclusion paragraphs) and put citations in latex format with a bibliography and precede alignment tab \& with the backslash to avoid latex errors.  Note \$ signs should be escaped with the backslash, forward double quotes should use two forward single quotes which is needed in latex.
	
	\subsection{Dynamic Array Functions}
	\href{https://exceljet.net/articles/dynamic-array-formulas-in-excel}{Dynamic array formulas} are a powerful way to deal with arbitrary size data. 
	
	\begin{enumerate}
		\item \texttt{FILTER}: Filters data and returns matching records.
		\item \texttt{RANDARRAY}: Generates an array of random numbers.
		\item \texttt{SEQUENCE}: Generates an array of sequential numbers.
		\item \texttt{SORT}: Sorts a range by column.
		\item \texttt{SORTBY}: Sorts a range by another range or array.
		\item \texttt{UNIQUE}: Extracts unique values from a list or range.
		\item \texttt{XLOOKUP}: A modern replacement for \texttt{VLOOKUP}.
		\item \texttt{XMATCH}: A modern replacement for the \texttt{MATCH} function.
		\item \texttt{ARRAYTOTEXT}: Converts an array to text.
		\item \texttt{BYCOL}: Applies a lambda function to each column in an array.
		\item \texttt{BYROW}: Applies a lambda function to each row in an array.
		\item \texttt{CHOOSECOLS}: Selects columns from an array.
		\item \texttt{CHOOSEROWS}: Selects rows from an array.
		\item \texttt{DROP}: Drops the first \texttt{n} rows or columns from an array.
		\item \texttt{EXPAND}: Expands an array by adding rows or columns.
		\item \texttt{HSTACK}: Stacks arrays horizontally.
		\item \texttt{ISOMITTED}: Checks if a value is omitted.
		\item \texttt{LAMBDA}: Creates a custom function.
		\item \texttt{LET}: Assigns names to calculation results.
		\item \texttt{MAKEARRAY}: Creates an array of a given size.
		\item \texttt{MAP}: Applies a lambda function to each item in an array.
		\item \texttt{REDUCE}: Reduces an array to a single value.
		\item \texttt{SCAN}: Scans an array and reduces it to a single value.
		\item \texttt{STOCKHISTORY}: Returns historical stock prices.
		\item \texttt{TAKE}: Takes the first \texttt{n} rows or columns from an array.
		\item \texttt{TEXTAFTER}: Returns the text after a delimiter.
		\item \texttt{TEXTBEFORE}: Returns the text before a delimiter.
		\item \texttt{TEXTSPLIT}: Splits text into an array.
		\item \texttt{TOCOL}: Converts a single row array to a single column.
		\item \texttt{TOROW}: Converts a single column array to a single row.
		\item \texttt{VALUETOTEXT}: Converts a value to text.
		\item \texttt{VSTACK}: Stacks arrays vertically.
		\item \texttt{WRAPCOLS}: Wraps a single column array into multiple columns.
		\item \texttt{WRAPROWS}: Wraps a single row array into multiple rows.
	\end{enumerate}
	
	Please note that these functions are only available in Excel 365 and Excel 2021. They are not available in Excel 2019 and earlier versions.
	
	\subsection{Excluding D Component equals Material from the count}
	
	
	\subsubsection{Introduction}
	
	Dynamic counters are important to prevent end row or column counting.
	
	\begin{lstlisting}[
		caption={Dynamic counter of SQL pulled data column}, label=Dynamic counter of SQL data column, 
		linewidth=\columnwidth, breaklines=true, 
		language=Excel]
		=UNIQUE(
		FILTER(
		INDIRECT("DR!" & CHAR(64 + MATCH(D3, DR!$2:$2, 0)) & "$3:" & CHAR(64 + MATCH(D3, DR!$2:$2, 0)) & ROW(INDEX(DR!$A:$A, 'Par1'!$N$1))),
		(INDIRECT("DR!" & CHAR(64 + MATCH("D Component", DR!$2:$2, 0)) & "$3:" & CHAR(64 + MATCH("D Component", DR!$2:$2, 0)) & ROW(INDEX(DR!$A:$A, 'Par1'!$N$1))) <>
		INDIRECT("DR!" & CHAR(64 + MATCH("Material #", DR!$2:$2, 0)) & "$3:" & CHAR(64 + MATCH("Material #", DR!$2:$2, 0)) & ROW(INDEX(DR!$A:$A,'Par1'!$N$1))))
		)
		)
	\end{lstlisting}
	
	Looking at Listing~\ref{Dynamic counter of SQL data column} we see a complex combination of functions that aims to filter and extract unique values from a dynamically defined range in the \texttt{DR} sheet, based on multiple conditions. Here’s a detailed breakdown of the formula.
	
	\subsubsection{Explanation}
	
	\begin{enumerate}
		\item \textbf{MATCH(D3, DR!\$2:\$2, 0)}:
		\begin{itemize}
			\item Finds the column number in the \texttt{DR} sheet where the header matches the value in cell \texttt{D3}.
		\end{itemize}
		
		\item \textbf{CHAR(64 + MATCH(D3, DR!\$2:\$2, 0))}:
		\begin{itemize}
			\item Converts the column number to a corresponding letter (e.g., 1 becomes A, 2 becomes B).
		\end{itemize}
		
		\item \textbf{INDIRECT(``DR!" \& CHAR(64 + MATCH(D3, DR!\$2:\$2, 0)) \& ``\$3:" \& CHAR(64 + MATCH(D3, DR!\$2:2, 0)) \& ROW(INDEX(DR!\$A:\$A, 'Par1'!\$N\$1)))}:
		\begin{itemize}
			\item Constructs a range reference in the \texttt{DR} sheet starting from row 3 to the row number specified in \texttt{'Par1'!\$N\$1} for the column found in the previous step.
			\item This INDIRECT function dynamically constructs a range to be used in the FILTER function.
		\end{itemize}
		
		\item \textbf{FILTER(..., (Condition))}:
		\begin{itemize}
			\item Filters the range defined by the INDIRECT function based on a condition.
		\end{itemize}
		
		\item \textbf{Condition}:
		\begin{itemize}
			\item \texttt{(INDIRECT("DR!" \& CHAR(64 + MATCH("D Component", DR!\$2:\$2, 0)) \& "\$3:" \& CHAR(64 + MATCH("D Component", DR!\$2:\$2, 0)) \& ROW(INDEX(DR!\$A:\$A, 'Par1'!\$N\$1))) <> INDIRECT("DR!" \& CHAR(64 + MATCH("Material \#", DR!\$2:\$2, 0)) \& "\$3:" \& CHAR(64 + MATCH("Material \#", DR!\$2:\$2, 0)) \& ROW(INDEX(DR!\$A:\$A,'Par1'!\$N\$1))))}:
			\begin{itemize}
				\item Constructs two additional ranges for columns where the headers are ``D Component" and ``Material \#" respectively.
				\item Compares the values in these columns row by row.
				\item The condition checks where the value in the ``D Component" column is not equal to the value in the ``Material \#" column.
			\end{itemize}
		\end{itemize}
		
		\item \textbf{UNIQUE(...)}:
		\begin{itemize}
			\item Extracts unique values from the filtered results to ensure there are no duplicates.
		\end{itemize}
	\end{enumerate}
	
	\subsubsection{Summary}
	
	\begin{itemize}
		\item The formula dynamically references columns in the \texttt{DR} sheet based on the headers specified in cell \texttt{D3}, "D Component", and "Material \#".
		\item It creates ranges starting from row 3 to a row number defined in \texttt{'Par1'!$N$1}.
		\item It filters the values in the dynamically referenced column (from \texttt{D3}) where the value in the "D Component" column is not equal to the value in the "Material \#" column.
		\item Finally, it returns a list of unique values that meet these conditions.
	\end{itemize}
	
	This formula is quite powerful and flexible, allowing dynamic column and row referencing, filtering based on complex conditions, and ensuring the results are unique.
	
	\begin{thebibliography}{9}
		\bibitem{excel_office}
		Microsoft Office Support, \emph{Excel Functions}, Available at: \url{https://support.microsoft.com/excel}
	\end{thebibliography}
	
	
	\subsection{Improving the count}
	
	
	\begin{lstlisting}[
		caption={Counts occurrences of values in a specified range, excluding rows where the ``Material" column has the same value}, label=Counts occurrences of values in a specified range,
		linewidth=\columnwidth, breaklines=true, 
		language=Excel]
		=LET(
		fColumn, D4:INDEX(D:D, D2 - 2),
		dataColIndex, MATCH(D3, DR!$2:$2, 0),
		matColIndex, MATCH("Material #", DR!$2:$2, 0),
		dataRange, INDIRECT("DR!" & CHAR(64 + dataColIndex) & "3:" & CHAR(64 + dataColIndex) & $N$1),
		matRange, INDIRECT("DR!" & CHAR(64 + matColIndex) & "3:" & CHAR(64 + matColIndex) & $N$1),
		counts, MAP(
		fColumn,
		LAMBDA(fValue,
		SUM((dataRange = fValue) * (matRange <> fValue))
		)
		),
		IFERROR(counts, "No Matches")
		)	
	\end{lstlisting} 
	
	This code uses Excel's `LET`, `MATCH`, `INDIRECT`, `MAP`, `LAMBDA`, and `IFERROR` functions to dynamically calculate counts of values in a specified range based on certain conditions. Here's a step-by-step breakdown of what the code does:
	
	\subsubsection*{Description}
	
	\begin{enumerate}
		\item \textbf{LET Function}:
		\begin{itemize}
			\item \texttt{LET} allows you to define variables and use them in subsequent calculations, making the formula easier to read and more efficient.
		\end{itemize}
		
		\item \textbf{Variables Defined}:
		\begin{itemize}
			\item \textbf{fColumn}: This variable represents a range from \texttt{D4} to the cell that is \texttt{(D2 - 2)} rows down in column \texttt{D}. It essentially creates a dynamic range based on the value in cell \texttt{D2}.
			\item \textbf{dataColIndex}: This variable stores the column index of the column in the \texttt{DR} sheet that matches the header specified in cell \texttt{D3}. The \texttt{MATCH} function is used to find this column index.
			\item \textbf{matColIndex}: This variable stores the column index of the ``Material \#'' column in the \texttt{DR} sheet. The \texttt{MATCH} function is used to find this column index.
			\item \textbf{dataRange}: This variable creates a dynamic range in the \texttt{DR} sheet from row 3 to the row specified by \texttt{\$N\$1}, for the column identified by \texttt{dataColIndex}. The \texttt{INDIRECT} and \texttt{CHAR} functions are used to create this range.
			\item \textbf{matRange}: This variable creates a dynamic range in the \texttt{DR} sheet from row 3 to the row specified by \texttt{\$N\$1}, for the column identified by \texttt{matColIndex}. The \texttt{INDIRECT} and \texttt{CHAR} functions are used to create this range.
			\item \textbf{counts}: This variable uses the \texttt{MAP} function to iterate over each value in \texttt{fColumn}. For each value, it uses a \texttt{LAMBDA} function to calculate the sum of the conditions \texttt{(dataRange = fValue)} and \texttt{(matRange <> fValue)}. This essentially counts how many times each value in \texttt{fColumn} appears in \texttt{dataRange}, excluding rows where the ``Material \#'' column has the same value as \texttt{fValue}.
		\end{itemize}
		
		\item \textbf{MAP Function}:
		\begin{itemize}
			\item \texttt{MAP} takes the range \texttt{fColumn} and applies the \texttt{LAMBDA} function to each element.
			\item \texttt{LAMBDA(fValue, SUM((dataRange = fValue) * (matRange <> fValue)))}: For each \texttt{fValue} in \texttt{fColumn}, it calculates how many times \texttt{fValue} appears in \texttt{dataRange}, excluding rows where \texttt{matRange} has the same value as \texttt{fValue}.
		\end{itemize}
		
		\item \textbf{IFERROR Function}:
		\begin{itemize}
			\item \texttt{IFERROR(counts, ``No Matches'')}: If any errors occur during the calculation of \texttt{counts}, it returns ``No Matches''.
		\end{itemize}
	\end{enumerate}
	
	\subsubsection*{Summary}
	
	\begin{itemize}
		\item \textbf{Purpose}: The formula counts occurrences of values in a specified range, excluding rows where the ``D Component'' and ``Material \#'' columns have the same values.
		\item \textbf{Input}:
		\begin{itemize}
			\item \texttt{D4} to a dynamically calculated cell in column \texttt{D} based on \texttt{D2}.
			\item \texttt{D3}: Header name to match in the \texttt{DR} sheet.
			\item ``Material \#'': Static header name to match in the \texttt{DR} sheet.
			\item \texttt{\$N\$1}: Determines the last row for the ranges.
		\end{itemize}
		\item \textbf{Output}: An array of counts, each representing the number of times each value in \texttt{fColumn} appears in \texttt{dataRange}, excluding rows where \texttt{matRange} has the same value as the current value.
	\end{itemize}
	
	\subsubsection*{Example}
	
	If \texttt{D3} contains ``Component'' and \texttt{D2} contains 100, the formula will:
	\begin{enumerate}
		\item Calculate the range \texttt{D4:D98}.
		\item Find the column index in \texttt{DR} where the header is ``Component''.
		\item Find the column index in \texttt{DR} where the header is ``Material \#''.
		\item Create dynamic ranges for these columns from row 3 to the row specified in \texttt{\$N\$1}.
		\item Iterate over each value in \texttt{D4:D98}, counting how many times it appears in the ``Component'' column of \texttt{DR}, excluding rows where the ``Material \#'' column has the same value.
	\end{enumerate}
	
	This formula is useful for performing conditional counts with complex criteria in a dynamic and readable manner.
	
	\subsubsection*{Conclusion}
	
	The given code snippet effectively uses Excel's advanced functions to dynamically calculate counts of values based on specified conditions. By defining variables with the \texttt{LET} function and applying the \texttt{MAP} and \texttt{LAMBDA} functions for iterative calculations, the formula remains both efficient and easy to read. This approach can be particularly useful for complex data analysis tasks in Excel.
	
	\begin{thebibliography}{9}
		\bibitem{excel-functions} Microsoft Excel Documentation. Available at: https://support.microsoft.com/excel
		\bibitem{advanced-excel} Advanced Excel Functions. Available at: https://www.excel-easy.com/functions
	\end{thebibliography}
	
	\subsection{Improving the percent}
	
	\begin{lstlisting}[
		caption={pdf calc}, label=pdf calc, 
		linewidth=\columnwidth, breaklines=true, 
		language=Excel]
		=LET(
		data_range, E4:INDEX(E4:E$1048576, MATCH(TRUE, ISBLANK(E4:E$1048576), 0) - 1),
		total, SUM(data_range),
		percentages, data_range / total * 100,
		percentages
		)
	\end{lstlisting}
	
	\subsection{Remove the filter for blank cells}
	
				
	
	% that's all folks
\end{document}			% \fi
				
				
				
				% that's all folks
			\end{document}
			
			%\fi

**Comment by sunderme** [comment]
what about all the `\input` files ? Can you upload the files ? The example above is skewed by github markdown interpretation.

**Comment by jeffspieg** [comment]
If the problem is in the tex editor you shouldn't need to compile,  Why do you need the input files?

**Comment by muzimuzhi** [comment]
@jeffspieg It's always recommended to mark code snippets/examples as Markdown [Fenced code blocks](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks#fenced-code-blocks).

Unfortunately, still not reproducible with your snippet, using TeXstudio 4.8.2alpha4. Can you check with 4.8.1 and 4.8.2alpha4? Does the wrong highlighting appears right after you opened the tex file without taking any other actions? It seems the steps to reproduce what you reported is still uncovered.

<details><summary>Example using <code>lstlistings</code>, v2</summary>
<p>

```tex
\documentclass{IEEEtran}
\usepackage{listings}

\input{../Autotestcon/preamble}
\RCRtrue

\input{../Autotestcon/documentclass}

\printtrue

\input{../Autotestcon/pkg}

\begin{document}
\bibliographystyle{IEEEtran}
%
% paper title
% can use linebreaks \ within to get better formatting as desired
% make the title area
\title{Texstudio green bug}
\maketitle

\subsubsection{Introduction}

Dynamic counters are important to prevent end row or column counting.

\begin{lstlisting}[
	caption={Dynamic counter of SQL pulled data column}, label=Dynamic counter of SQL data column, 
	linewidth=\columnwidth, breaklines=true, 
	language=Excel]
	=UNIQUE(
	FILTER(
	INDIRECT("DR!" & CHAR(64 + MATCH(D3, DR!$2:$2, 0)) & "$3:" & CHAR(64 + MATCH(D3, DR!$2:$2, 0)) & ROW(INDEX(DR!$A:$A, 'Par1'!$N$1))),
	(INDIRECT("DR!" & CHAR(64 + MATCH("D Component", DR!$2:$2, 0)) & "$3:" & CHAR(64 + MATCH("D Component", DR!$2:$2, 0)) & ROW(INDEX(DR!$A:$A, 'Par1'!$N$1))) <>
	INDIRECT("DR!" & CHAR(64 + MATCH("Material #", DR!$2:$2, 0)) & "$3:" & CHAR(64 + MATCH("Material #", DR!$2:$2, 0)) & ROW(INDEX(DR!$A:$A,'Par1'!$N$1))))
	)
	)
\end{lstlisting}

Looking at Listing~\ref{Dynamic counter of SQL data column} we see a complex combination of functions that aims to filter and extract unique values from a dynamically defined range in the \texttt{DR} sheet, based on multiple conditions. Here’s a detailed breakdown of the formula.

			

% that's all folks
\end{document} % \fi
```

</p>
</details>

![image](https://github.com/user-attachments/assets/f3ab64dc-ec16-4929-baed-9c451a6acb6a)

**Comment by sunderme** [comment]
txs loads cwl files depending on the \usepackage commands. Since you do not provide a complete document, default packages are loaded which does not include `listings` (so here your example does not make much sense unless I start to guess what packages are loaded).
Please provide and **test** minimal example which really works as stand-alone example. **Do not make assumptions. The example needs to be open on your side with no external inputs. txs scans all inputs and interprets usepackages and more, so that does have an influence on the outcome.**

**Comment by jeffspieg** [comment]
Thanks Sunderme.  I see your point as txs does can all inputs!  This code can be compiled too and shows the error even with the lstefinelanguage if you'd like.

%\input{../Autotestcon/preamble}
%\RCRtrue

%\input{../Autotestcon/documentclass}
\documentclass[journal]{IEEEtran}

%\printtrue

%\input{../Autotestcon/pkg}

\usepackage{listings}

\lstdefinelanguage{Excel} {
	morekeywords={
		A\$1048576, B\$1048576, C\$1048576, D\$1048576, E\$1048576, F\$1048576, G\$1048576, H\$1048576, I\$1048576, J\$1048576, K\$1048576, L\$1048576, M\$1048576,
		N\$1048576, O\$1048576, P\$1048576, Q\$1048576, R\$1048576, S\$1048576, T\$1048576, U\$1048576, V\$1048576, W\$1048576, X\$1048576, Y\$1048576, Z\$1048576,
		AND, ARRAYTOTEXT,
		AVERAGE, BYCOL,
		BYROW, CHAR,
		CHOOSE, CHOOSECOLS,
		CHOOSEROWS, COUNTA,
		COUNTIF, DROP,
		EXPAND, FILTER,
		HSTACK, IF,
		IFERROR, INDEX,
		INDEX, INDIRECT,
		ISBLANK, ISNUMBER, ISOMITTED,
		LAMBDA, LET,
		LOOKUP, MAKEARRAY,
		MAP, MATCH, MIN
		OR, RANDARRAY,
		REDUCE, ROW, SCAN,
		SEQUENCE, SORT,
		SORTBY, STOCKHISTORY,
		SUM, TAKE, TEXT, TEXTJOIN
		TEXTAFTER, TEXTBEFORE,
		TEXTSPLIT, TOCOL,
		TOROW, UNIQUE,
		VALUETOTEXT, VLOOKUP,
		VSTACK, WRAPCOLS,
		WRAPROWS, XLOOKUP
		XMATCH
	},
	sensitive=false,
	morecomment=[l]{//},
	morestring=[b]",
}



\begin{document}

	\title{Texstudio green bug}
	\maketitle
	

	\subsubsection{Introduction}
	
	Dynamic counters are important to prevent end row or column counting.
	
	\begin{lstlisting}[
		caption={Dynamic counter of SQL pulled data column}, label=Dynamic counter of SQL data column, 
		linewidth=\columnwidth, breaklines=true, 
		language=Excel]
		=UNIQUE(
		FILTER(
		INDIRECT("DR!" & CHAR(64 + MATCH(D3, DR!$2:$2, 0)) & "$3:" & CHAR(64 + MATCH(D3, DR!$2:$2, 0)) & ROW(INDEX(DR!$A:$A, 'Par1'!$N$1))),
		(INDIRECT("DR!" & CHAR(64 + MATCH("D Component", DR!$2:$2, 0)) & "$3:" & CHAR(64 + MATCH("D Component", DR!$2:$2, 0)) & ROW(INDEX(DR!$A:$A, 'Par1'!$N$1))) <>
		INDIRECT("DR!" & CHAR(64 + MATCH("Material #", DR!$2:$2, 0)) & "$3:" & CHAR(64 + MATCH("Material #", DR!$2:$2, 0)) & ROW(INDEX(DR!$A:$A,'Par1'!$N$1))))
		)
		)
	\end{lstlisting}
	
	Looking at Listing~\ref{Dynamic counter of SQL data column} we see a complex combination of functions that aims to filter and extract unique values from a dynamically defined range in the \texttt{DR} sheet, based on multiple conditions. Here’s a detailed breakdown of the formula.
	
				
	
	% that's all folks
\end{document}			% \fi

**Comment by sunderme** [comment]
just by entering or reloading the code, I see no issue with the highlighting.
<img width="1477" alt="grafik" src="https://github.com/user-attachments/assets/c47521cf-04a2-425d-8a30-249651812c39">

**Comment by jeffspieg** [comment]
![image](https://github.com/user-attachments/assets/b797a066-10f0-4933-a59b-b4c6f932e522)

For me this code has the text the wrong color.

**Comment by sunderme** [comment]
the task at hand is to reproduce the issue.

so
1. you have only the test document open, no other open files
2. no changed configuration
3. when you start txs and the session with the single test file is restored, the syntax highlighting is as you show it ?

**Comment by jeffspieg** [comment]
1. Yes. 2. Yes. 3. No.  
When I restarted on this file the problem went away.  But going back to the file where I took this code the problem still exists for 1-3.  I will have to make a better example.

**Comment by jeffspieg** [comment]
While working on a better example I found the following:
When I comment out \input{../Autotestcon/pkg}, the Green runaway font color change in Texstudio goes away.  
When i uncomment it then it comes back.  If I put everything inside pkg into a comment and save the file, the Green runaway still occurs!  Why is that ?  It is an empty file?

\input{../Autotestcon/preamble}
\input{../Autotestcon/documentclass}
\input{../Autotestcon/pkg}


I changed pkg to \input{../Autotestcon/pkg2} then back to pkg and it crashed.  Note pkg2 did  not exist, but Texstudio crashes going back to the original similar to this backtrace:

Here's the back trace:
unknown at 7ff7fbbf30f0 (TXS-Version 4.8.0 R )
[bt] 00007ff7fbb3d4a5  q+3585657
[bt] 00007ff7fbb3c6b7  q+3582091
[bt] 00007ff7fba539e9  q+2628541
[bt] 000001d8190d89f0  ??? error: 126

Saved pkg to pkgGrreen and then while changing \input{../Autotestcon/pkg} to \input{../Autotestcon/pkgGreen} just typing in Texstudio the application crashes.  FYI I have never seen 4.8.0 crash before so I think we are getting closer:
![Texstudio crash](https://github.com/user-attachments/assets/ca4de31b-2e53-4b43-aa99-15cf93483068)

Texstudio is getting very adverserial the closer I get to the cause.   I don't want to give the full pkg file but wanted to divide and conquer the location that is problematic.  Unfortunately I found even with no contents the file is a problem.

**Comment by sunderme** [comment]
you can send larger test cases directly to me for debug.
They handled confidentially.

**Comment by sunderme** [comment]
not been able to reproduce
a crash was fixed

**Comment by jeffspieg** [comment]
This is still a problem although I found a work around.  Here is a self-contained .tex tile that will show you the problem after the second listing:

%\input{../Autotestcon/preamble}
\newif\ifRCR
\newif\ifprint
\newif\ifTEXold
\printfalse
\RCRtrue

%\input{../Autotestcon/documentclass}
\documentclass[journal]{IEEEtran}

\printtrue

%\input{../Autotestcon/pkgGreen}
\usepackage{listings}
%\lstset{basicstyle=\small\ttfamily,columns=fullflexible}
%\lstset{columns=fullflexible,frame=single,captionpos=b}
%\lstdefinestyle{sharpc}{language=[Sharp]C, frame=lr, rulecolor=\color{blue!80!black}}
%\lstset{columns=fullflexible,captionpos=b,showstringspaces=false,basicstyle=\ttfamily}

\lstdefinelanguage{Excel} {
	morekeywords={
		A\$1048576, B\$1048576, C\$1048576, D\$1048576, E\$1048576, F\$1048576, G\$1048576, H\$1048576, I\$1048576, J\$1048576, K\$1048576, L\$1048576, M\$1048576,
		N\$1048576, O\$1048576, P\$1048576, Q\$1048576, R\$1048576, S\$1048576, T\$1048576, U\$1048576, V\$1048576, W\$1048576, X\$1048576, Y\$1048576, Z\$1048576,
		AND, ARRAYTOTEXT,
		AVERAGE, BYCOL,
		BYROW, CHAR,
		CHOOSE, CHOOSECOLS,
		CHOOSEROWS, COUNTA,
		COUNTIF, DROP,
		EXPAND, FILTER,
		HSTACK, IF,
		IFERROR, INDEX,
		INDEX, INDIRECT,
		ISBLANK, ISNUMBER, ISOMITTED,
		LAMBDA, LET,
		LOOKUP, MAKEARRAY,
		MAP, MATCH, MIN
		OR, RANDARRAY,
		REDUCE, ROW, SCAN,
		SEQUENCE, SORT,
		SORTBY, STOCKHISTORY,
		SUM, TAKE, TEXT, TEXTJOIN
		TEXTAFTER, TEXTBEFORE,
		TEXTSPLIT, TOCOL,
		TOROW, UNIQUE,
		VALUETOTEXT, VLOOKUP,
		VSTACK, WRAPCOLS,
		WRAPROWS, XLOOKUP
		XMATCH
	},
	sensitive=false,
	morecomment=[l]{//},
	morestring=[b]",
}


\lstset{columns=fullflexible,captionpos=b,showstringspaces=false,basicstyle=\ttfamily\small, numbers=left, numberstyle=\tiny, stepnumber=5, numberfirstline=false, firstnumber=2, numbersep=5pt, breaklines=true}




\begin{document}

	\title{Texstudio green bug}
	\maketitle
	

	\subsubsection{Introduction}
	
	Dynamic counters are important to prevent end row or column counting.
	
	\begin{lstlisting}[
		caption={Dynamic counter of SQL pulled data column}, label=Dynamic counter of SQL data column, 
		linewidth=\columnwidth, breaklines=true, 
		language=Excel]
		=UNIQUE(
		FILTER(
		INDIRECT("DR!" & CHAR(64 + MATCH(D3, DR!$2:$2, 0)) & "$3:" & CHAR(64 + MATCH(D3, DR!$2:$2, 0)) & ROW(INDEX(DR!$A:$A, 'Par1'!$N$1))),
		(INDIRECT("DR!" & CHAR(64 + MATCH("D Component", DR!$2:$2, 0)) & "$3:" & CHAR(64 + MATCH("D Component", DR!$2:$2, 0)) & ROW(INDEX(DR!$A:$A, 'Par1'!$N$1))) <>
		INDIRECT("DR!" & CHAR(64 + MATCH("Material #", DR!$2:$2, 0)) & "$3:" & CHAR(64 + MATCH("Material #", DR!$2:$2, 0)) & ROW(INDEX(DR!$A:$A,'Par1'!$N$1))))))
				
	\end{lstlisting}
	
	By adding a blank line before \begin{verbatim}\end{lstlisting}\end{verbatim} then I can get rid of the green text.
	
	
\begin{lstlisting}[caption={Conditional formatting rule for pareto tables}, label=Cfrules1, linewidth=\columnwidth, breaklines=true, language=Excel]  
	=OR(W3<=20, AND(W2<20, W3>=20)):  
	with W helper column 
	=SUM(V$3:V3).  
	Better to use a dynamic array in the helper column:
	=LET(
	firstBlank, MATCH(TRUE, INDEX(U3:U100="",), 0),
	adjustedRange, SEQUENCE(firstBlank - 1, 1, 3),
	SCAN(0, INDEX(V:V, adjustedRange), LAMBDA(a,b, a + b))
	=LET(
	firstBlank, MATCH(TRUE, INDEX(U3:U100="",), 0),
	adjustedRange, SEQUENCE(firstBlank - 1, 1, 3),
	SCAN(0, INDEX(V:V, adjustedRange), LAMBDA(a,b, a + b))
\end{lstlisting}
	
	Looking at Listing~\ref{Dynamic counter of SQL data column} we see a complex combination of functions that aims to filter and extract unique values from a dynamically defined range in the \texttt{DR} sheet, based on multiple conditions. Here’s a detailed breakdown of the formula.
	
				
	
	% that's all folks
\end{document}			% \fi

**Comment by jeffspieg** [comment]
Reopen issue #3762 as I added a new example

**Comment by sunderme** [comment]
?

<img width="820" alt="grafik" src="https://github.com/user-attachments/assets/f75e1d84-3e7e-41b3-8c72-d938c26c5976">

**Comment by sunderme** [comment]
How do I see an issue ?
<img width="820" alt="grafik" src="https://github.com/user-attachments/assets/e4b0902e-9597-45fa-9bb3-3995adfaec37">

**Comment by jeffspieg** [comment]
%\input{../Autotestcon/preamble}
\newif\ifRCR
\newif\ifprint
\newif\ifTEXold
\printfalse
\RCRtrue

%\input{../Autotestcon/documentclass}
\documentclass[journal]{IEEEtran}

\printtrue

%\input{../Autotestcon/pkgGreen}
\usepackage{listings}
%\lstset{basicstyle=\small\ttfamily,columns=fullflexible}
%\lstset{columns=fullflexible,frame=single,captionpos=b}
%\lstdefinestyle{sharpc}{language=[Sharp]C, frame=lr,
rulecolor=\color{blue!80!black}}
%\lstset{columns=fullflexible,captionpos=b,showstringspaces=false,basicstyle=\ttfamily}

\lstdefinelanguage{Excel} {
morekeywords={
A\$1048576, B\$1048576, C\$1048576, D\$1048576, E\$1048576, F\$1048576,
G\$1048576, H\$1048576, I\$1048576, J\$1048576, K\$1048576, L\$1048576,
M\$1048576,
N\$1048576, O\$1048576, P\$1048576, Q\$1048576, R\$1048576, S\$1048576,
T\$1048576, U\$1048576, V\$1048576, W\$1048576, X\$1048576, Y\$1048576,
Z\$1048576,
AND, ARRAYTOTEXT,
AVERAGE, BYCOL,
BYROW, CHAR,
CHOOSE, CHOOSECOLS,
CHOOSEROWS, COUNTA,
COUNTIF, DROP,
EXPAND, FILTER,
HSTACK, IF,
IFERROR, INDEX,
INDEX, INDIRECT,
ISBLANK, ISNUMBER, ISOMITTED,
LAMBDA, LET,
LOOKUP, MAKEARRAY,
MAP, MATCH, MIN
OR, RANDARRAY,
REDUCE, ROW, SCAN,
SEQUENCE, SORT,
SORTBY, STOCKHISTORY,
SUM, TAKE, TEXT, TEXTJOIN
TEXTAFTER, TEXTBEFORE,
TEXTSPLIT, TOCOL,
TOROW, UNIQUE,
VALUETOTEXT, VLOOKUP,
VSTACK, WRAPCOLS,
WRAPROWS, XLOOKUP
XMATCH
},
sensitive=false,
morecomment=[l]{//},
morestring=[b]",
}


\lstset{columns=fullflexible,captionpos=b,showstringspaces=false,basicstyle=\ttfamily\small,
numbers=left, numberstyle=\tiny, stepnumber=5, numberfirstline=false,
firstnumber=2, numbersep=5pt, breaklines=true}




\begin{document}

\title{Texstudio green bug}
\maketitle

\subsubsection{Introduction}
Dynamic counters are important to prevent end row or column counting.
\begin{lstlisting}[
caption={Dynamic counter of SQL pulled data column}, label=Dynamic counter
of SQL data column,
linewidth=\columnwidth, breaklines=true,
language=Excel]
=UNIQUE(
FILTER(
INDIRECT("DR!" & CHAR(64 + MATCH(D3, DR!$2:$2, 0)) & "$3:" & CHAR(64 +
MATCH(D3, DR!$2:$2, 0)) & ROW(INDEX(DR!$A:$A, 'Par1'!$N$1))),
(INDIRECT("DR!" & CHAR(64 + MATCH("D Component", DR!$2:$2, 0)) & "$3:" &
CHAR(64 + MATCH("D Component", DR!$2:$2, 0)) & ROW(INDEX(DR!$A:$A,
'Par1'!$N$1))) <>
INDIRECT("DR!" & CHAR(64 + MATCH("Material #", DR!$2:$2, 0)) & "$3:" &
CHAR(64 + MATCH("Material #", DR!$2:$2, 0)) &
ROW(INDEX(DR!$A:$A,'Par1'!$N$1))))))
\end{lstlisting}
By adding a blank line before
\begin{verbatim}\end{lstlisting}\end{verbatim} then I can get rid of the
green text.
\begin{lstlisting}[caption={Conditional formatting rule for pareto tables},
label=Cfrules1, linewidth=\columnwidth, breaklines=true, language=Excel]
=OR(W3<=20, AND(W2<20, W3>=20)):
with W helper column
=SUM(V$3:V3).
Better to use a dynamic array in the helper column:
=LET(
firstBlank, MATCH(TRUE, INDEX(U3:U100="",), 0),
adjustedRange, SEQUENCE(firstBlank - 1, 1, 3),
SCAN(0, INDEX(V:V, adjustedRange), LAMBDA(a,b, a + b))
=LET(
firstBlank, MATCH(TRUE, INDEX(U3:U100="",), 0),
adjustedRange, SEQUENCE(firstBlank - 1, 1, 3),
SCAN(0, INDEX(V:V, adjustedRange), LAMBDA(a,b, a + b))
\end{lstlisting}
Looking at Listing~\ref{Dynamic counter of SQL data column} we see a
complex combination of functions that aims to filter and extract unique
values from a dynamically defined range in the \texttt{DR} sheet, based on
multiple conditions. Here’s a detailed breakdown of the formula.
% that's all folks
\end{document} % \fi

**Comment by jeffspieg** [comment]
Just put the tex i sent into texstudio.  the bottom half stays green when
it shouldn't

**Comment by octaeder** [comment]
That's what I see:

![image](https://github.com/user-attachments/assets/c074ed57-17f0-43a1-b34e-be80606d6ded)

Win10/MikTex
TeXstudio 4.8.5 (git 4.8.5alpha1-29-gb7ef6508a)
Using Qt Version 6.7.2, compiled with Qt 6.7.2 R

**Comment by octaeder** [comment]
Do you follow the same procedure as I do? Start txs (best without any previous documents), open a new editor and paste the code from here, that you have posted before. Then, what is the coloring?
