### ISSUE TITLE
find and replace only replaces in one line

### ISSUE THREAD

**Issue by lashkevi** [texstudio-org/texstudio#861]
When I try to find and replace an expression by pressing the "replace and find next" button several times and then stops replacing. I mean, it continues finding next instants of the expression, but does not replace them. To continue replacements I need to move cursor somewhere and then proceed typing the "replace and find next" button.

### Environment
- TeXstudio: 2.12.18
- Qt: 5
- OS: OpenSUSE Linux, package texstudio-2.12.18-lp151.5.1.x86_64.rpm
- TeX distribution: texlive

### Expected behavior

"Replace and find next" button replaces an expression and jumps to the next instance.

### Actual behavior

After several replacements the "replace and find next" button behaves just like "find next" button.

### How to reproduce

1. Open any TeX file in TeXStudio.
2. Press Ctrl+R or click Edit->Search->Find and replace
3. Choose any expression, which enters the text many times, as a search expression.
4. Choose any other expression as replacement.
5. Multiply press the red down arrow "replace and find next".

![Screenshot_20200106_232546](https://user-images.githubusercontent.com/13115223/71846587-00a56880-30dc-11ea-99ee-4e2d9d59520a.png)

**Comment by dbitouze** [comment]
**Off-topic:** `$$...$$` shouldn't be used with LaTeX: use `\[...\]` instead. See [l2tabu](https://www.ctan.org/pkg/l2tabu-english).

**Comment by benibela** [comment]
Weird. I could reproduce it several times, but now it does not happen anymore without any change

It never seems to happen if the prompt option ( [?] button) is activated

**Comment by lashkevi** [comment]
I have never encountered this problem in TeXStudio 2.12.16 and earlier versions.

**Comment by lashkevi** [comment]
It does not actually make all replacements with pressed "?" button and use of "Replace all" button, even if I always confirm replacements.

**Comment by vob2** [comment]
Why was this issue closed?  What is the resolution?   The bug does not appear to be fixed, yet.

**Comment by sunderme** [comment]
It is fixed in the development tree
Dev. Snapshots are available, see texstudio.org

**Comment by vob2** [comment]
I am using TeXstudio 2.12.18 (git 2.12.18)
Using Qt Version 5.12.1, compiled with Qt 5.12.1 R

I updated it right after posting an issue.   

The issue is not fixed in that version.
