### ISSUE TITLE
Registry is not updated while installing the latest version

### ISSUE THREAD

**Issue by grace211296** [texstudio-org/texstudio#895]
### Environment
- TeXstudio:  2.12.22
- Qt:  
- OS:  Win 10,Win 8
- TeX distribution: 

### Expected behavior
After Installing the version 2.12.22 of Texstudio the registry version should update to 2.12.22.

### Actual behavior
After Installing the version 2.12.22 of Texstudio the registry version still remains as 2.12.18.

### How to reproduce
Download the Texstudion 2.12.22 version from github and install it. Once the installation done refresh the control panel and registry the version will be 2.12.18.

**Comment by sunderme** [comment]
fixed

**Comment by Saxomania** [comment]
not completely fixed - Texstudio 2.12.22 installed but under programs&features version 2.12.18 is shown but in app itself under about it shows 2.12.22
