### ISSUE TITLE
Windows - NSIS uninstaller wrong filename + no silent uninstall

### ISSUE THREAD

**Issue by Swarheley** [texstudio-org/texstudio#92]
### Environment
- TeXstudio: 2.12.8
- Qt: 5.8.0
- OS: Windows 10 - 1709
- TeX distribution:  texlive 2016

### Expected behavior
1. UI Uninstall via Control Panel -> Uninstall
2. Silent uninstall using "uninstaller.exe" /S

### Actual behavior
1. \<installdir\>\uninstall.exe not found. The uninstaller is located in \<installdir\>\uninstaller.exe instead.
2. Silent switch does not work, when running the uninstaller.exe

### How to reproduce
Install latest release, try to uninstall.

**Comment by sunderme** [comment]
the uninstaller name is fixed, the /S option should be there already

**Comment by dstirner** [comment]
The /S option doesn't work for the uninstaller.

**Comment by m-lindemann** [comment]
Hey,

is the problem resolved or only closed? I´ve just downloaded the installer from the website and all problems are still there.

Silent uninstall (/S) is not working
Wrong uninstaller name in registry
Quotes in publisher and version key
Useless text in name key

See also #92 (closed)

Is there a fixed version of the installer available?
